DROP DATABASE IF EXISTS yeticave;

CREATE DATABASE yeticave
CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci;

USE yeticave;

CREATE TABLE categories (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(128) NOT NULL,
    symbol_code VARCHAR(128) NOT NULL
) ENGINE = INNODB;

CREATE TABLE users (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(128) NOT NULL UNIQUE,
    name VARCHAR(128) NOT NULL,
    password_hash CHAR(64) NOT NULL,
    contacts VARCHAR(256),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = INNODB;

CREATE TABLE lots (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(128) NOT NULL,
    description VARCHAR(512) NOT NULL,
    img VARCHAR(128) NOT NULL,
    start_price INT UNSIGNED NOT NULL,
    date_end TIMESTAMP NOT NULL,
    bet_step INT UNSIGNED NOT NULL,
    user_id INT UNSIGNED NOT NULL,
    winner_id INT UNSIGNED,
    category_id INT UNSIGNED NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id, winner_id) REFERENCES users (id),
    FOREIGN KEY (category_id) REFERENCES categories (id)
) ENGINE = INNODB;

CREATE TABLE bets (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    price INT UNSIGNED NOT NULL,
    user_id INT UNSIGNED NOT NULL,
    lot_id INT UNSIGNED NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (id),
    FOREIGN KEY (lot_id) REFERENCES lots (id)
) ENGINE = INNODB;
